### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by gulyabani666** [mikylebaksh/phonk-trap-programming-traxx#1]
---
name: Feature request
about: Gulyabani
title: 'Boş Kafalar Girer Mezara'
labels: 'Neden Rec.'
assignees: mikylebaksh

---

**Overview**
It's a mix of phonk music with brutal vocals, it has catchy parts with heavy vocals in Turkish. 

**Link**
https://open.spotify.com/track/2dIDPeJC5V1z7OuDTJbD8v?si=L33M1T7oS-2CqNr9fhu8LA

**Comment by mikylebaksh** [comment]
Thanks for the request. 

I won't be adding it to the playlist as it will be hard to fit in with the flow of the playlist. I tend to try to keep heavily repeating chopped and screwed vocals. 

Not to say it's not bad. I really enjoyed the uniqueness of your style. Keep it up!
