### ISSUE TITLE
Hyrule - Concord Dawn playlist submission

### ISSUE THREAD

**Issue by Hyrule089** [mikylebaksh/phonk-trap-programming-traxx#3]
**Overview**
hey, i hope you're having a blessed day
i'd like to submit my new track to your playlist, i think it would fit to your playlist because its a wave phonk song with a chilly but not sleepy vibe, in case you like it, it would be really cool if you'd add it to the playlist
kind regards

**Link**
https://open.spotify.com/track/4NfuDez37DwElKNpn3K477?si=nW9KLjC1QV22HFZ3z7Yr_Q

**Comment by mikylebaksh** [comment]
That was a jam. Added to playlist
