### ISSUE TITLE
Phonk/trap/programming submission

### ISSUE THREAD

**Issue by Lapowski** [mikylebaksh/phonk-trap-programming-traxx#4]
Yo, I came across your Phonk/trap/programming playlist and noticed that I have a similar sound to a lot of the artists on there. 
I just dropped this song today, and I'd appreciate it if you considered it for your playlist. My email is Nlepkowski92@gmail.com if you need to contact me. Thanks in advance.

https://open.spotify.com/track/07ag3Qn0AT1xl8h4toJGky?si=LwpDZ61_SWWHp-HIBBVFVQ

**Comment by mikylebaksh** [comment]
I like your sound. Do you have any tracks that are more instrumental? I generally stick to mostly instrumental with chopped and screwed vocals. Vocals can break concentration when deep in code. You know what I mean?

**Comment by Lapowski** [comment]
Hey thanks for getting back to me, I just dropped a song a few days ago
that has a lot of cowbell in it but my vocals aren’t chopped and screwed,
but I understand what you mean.

**Comment by Sotgore** [comment]
Hi I just released a drift phonk album called I see your hand and I want to send you a few tracks for your playlist. https://open.spotify.com/track/6q4kZZqObLIjH3naHjpR7p?si=c87407864b2b4781 this is one of the most energy banger kind of The whole album has 11 tracks and each track describes a drift technique with a name and a mood check it out if you have time :)

**Comment by mikylebaksh** [comment]
@Sotgore thanks bud. i forgot to reply and mention i added some tracks from phonkalypse. cheers
