### ISSUE TITLE
Phonk Track submission

### ISSUE THREAD

**Issue by OGee-T** [mikylebaksh/phonk-trap-programming-traxx#5]
Hey man,
I am OGee-T, a phonk producer from France.
I saw your playlist on spotify, there are dope tracks in there!
I also release a lot of phonk tracks and I think you might like some !

Here is my latest track :
https://open.spotify.com/track/0lzH3P2taJhHf631ByWOiH
 
But there are more on my profile.

Thanks and have a good one !

**Comment by mikylebaksh** [comment]
Good stuff. PASS DAT / GET SHOT had some really nice vocal samples. Added. I'll be going through more of your stuff and adding as I vibe
