### ISSUE TITLE
spotify playlist submission

### ISSUE THREAD

**Issue by Sotgore** [mikylebaksh/phonk-trap-programming-traxx#6]
Hi me(Sotgore) and H_X_7 released a chill cowbell phonk track called "Arcade Phonk" and was wondering 
if it fits your playlist. H_X_7 is rising and got featured in the official spotify playlist so I am just riding the wave haha.

track link : https://open.spotify.com/track/3ZSHQhlj1A8XyzsatvzR2n?si=a446e6d28f4648c4
sotgore link : https://open.spotify.com/artist/7HP5slTHISgeFSm05rrPYL?si=ILYoz-wMSKePZ3BO4cPIBQ&dl_branch=1 
H_X_7 link : https://open.spotify.com/artist/0G86N13ri50Zxa1sLBsXl3?si=wS4dMmrMRpSFGmU5gO6f7Q&dl_branch=1

**Comment by mikylebaksh** [comment]
added! great music. i've got a few of your tracks on the playlist. thanks for the contribution
