### ISSUE TITLE
LAKE OF FIRE - SHERMSTICK

### ISSUE THREAD

**Issue by SHERMSTICK** [mikylebaksh/phonk-trap-programming-traxx#7]
**Overview**
LAKE OF FIRE is MIDWEST PHONK

**Link**
https://open.spotify.com/track/0a2eEFqM4i7jBSxRudQOj3?si=nKVuwiBnSBasVSYyP5wA1w

**Comment by mikylebaksh** [comment]
Thanks for the suggestion. I like the song, but won't add it to this playlist. Lots of vocals can interrupt flow state (at least for me). keep up the good work though
