### ISSUE TITLE
Track Submission

### ISSUE THREAD

**Issue by r3loadmusic** [mikylebaksh/phonk-trap-programming-traxx#8]
**Overview**
It's a very energic & vibey house track, with a little bit of phonk in it.

**Link**
https://open.spotify.com/track/0BC838eFLwLJ0qUlDGRVBY?si=f5af8f54d0474434

**Comment by mikylebaksh** [comment]
Thanks for the suggestion. I like the song, but doesn't fit the aesthetic of the playlist. If you create any mostly instrumental hip hop phonk, feel free to submit again
